---
# Module information
name: MSR LCC
description: LCC tool for renovation options, interface developed by SP.
moduleId: SP_LCC_v2.1.0.0
path: C:\Users\johannesma\Documents\!Ecodistr-ICT\MSR LCC\LCC.xls