---
# Information needed in order to connect to the IMB-hub
serverAdress: localhost #csocks://vps17642.public.cloudvps.com
port: 4000
federation: TNODemo #EcoDistrict
subScribedEventName: dashboard
publishedEventName: modules