---
# Module information
name: Renobuild (TEST)
description: Renoubuild a LCA tool for renovation options, developed by SP.
moduleId: SP_LCA_v2.1.0.1
path: C:\Users\johannesma\Documents\!Ecodistr-ICT\Renobuild\Renobuild v2.1.xlsx