---
# Module information
name: Renobuild
description: Renoubuild a LCA tool for renovation options, developed by SP.
moduleId: SP_LCC_v2.1.0.0
path: C:\Users\johannesma\Documents\!Ecodistr-ICT\Renobuild\Renobuild v.2.1.xlsx