---
# Module information
name: Renobuild (v 2.0)
description: Renoubuild a LCA tool for renovation options, developed by SP.
moduleId: SP_LCC_v2.0.0.0
path: C:\Users\johannesma\Documents\!Ecodistr-ICT\Renobuild\Renobuild v3\Renobuild Miljokalkyl Ecodistrictanpassad utkast 150601.xlsx