---
# Module information
name: Renobuild
description: Renoubuild a LCA tool for renovation options, developed by SP.
moduleId: SP_LCC_v1.0.0.8
path: C:\Users\johannesma\Documents\!Ecodistr-ICT\Renobuild\Renobuild Miljokalkyl final.xlsx 