---
# Information needed in order to connect to the IMB-hub
remoteHost:  vps17642.public.cloudvps.com
subScribedEventName: modules
publishedEventName: dashboard
aCertFile : C:\Users\johannesma\Documents\Dokument\!Ecodistr-ICT\Certificates\client-eco-district.pfx
aCertFilePassword : "&8dh48klosaxu90OKH"
aRootCertFile : C:\Users\johannesma\Documents\Dokument\!Ecodistr-ICT\Certificates\root-ca-imb.crt