---
# Module information
name: SP Affordability
description: ...
moduleId: SP_Affordability_v0.1
# path: C:\Users\johannesma\Documents\Dokument\!Ecodistr-ICT\Affordability\Affordability.xlsm
# path: L:\EcoDistr\Modules\Affordability\Affordability.xlsm
path: C:\Programutveckling\EcoDistr\Modules\Affordability\Affordability.xlsm