---
# Module information
name: Stockholm Green Area Factor
description: Calculates the Stockholm green area factor, with sub cathegories Biodiversity, Social value and Climate adaptation.
moduleId: Stockholm_Green_Area_Factor
path: C:\Users\johannesma\Documents\!Ecodistr-ICT\Green\Beräkningsmall Grönytefaktor_english.xls