---
# Module information
name: Mobility Module
description: 
moduleId: MobilityModule
path: C:\Users\johannesma\Documents\Dokument\!Ecodistr-ICT\Mobility\Mobility v1.0.xlsx #L:\EcoDistr\Modules\MobilityModule\Mobility v1.0.xlsx