---
# Module information
name: SP Berlin BAF
description: Calculates the Berlin biotope area factor, the module is developed by SP.
moduleId: SP_Berlin_BAF
path: C:\Users\johannesma\Documents\!Ecodistr-ICT\Green\Biotope area factor.xlsx