---
# Module information
name: Berlin BAF (TEST)
description: Calculates the Berlin biotope area factor, the module interface is developed by SP. Information about recommended target values can be found at http://www.stadtentwicklung.berlin.de/umwelt/landschaftsplanung/bff/en/anwendungsbereiche.shtml
moduleId: SP_Berlin_BAF 2
path: C:\Users\johannesma\Documents\!Ecodistr-ICT\Green\Biotope area factor.xlsx